# Generated by Django 5.0.14 on 2025-09-22 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('icerik', models.TextField()),
                ('hedef_kitle', models.CharField(choices=[('herkes', 'Herkes'), ('ogrenci', 'Öğrenciler'), ('ogretmen', 'Öğretmenler'), ('personel', 'Personel'), ('veli', 'Veliler')], default='herkes', max_length=20)),
                ('oncelik', models.CharField(choices=[('dusuk', 'Düşük'), ('normal', 'Normal'), ('yuksek', 'Yüksek'), ('acil', 'Acil')], default='normal', max_length=10)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('aktif', models.BooleanField(default=True)),
                ('son_gecerlilik', models.DateTimeField(blank=True, null=True)),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duyurular', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
