# Generated by Django 5.0.14 on 2025-09-22 18:07

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duyurular', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyuru',
            name='hedef_kitle',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ogrenci', 'Öğrenciler'), ('ogretmen', 'Öğretmenler'), ('muhasebe', 'Muhasebe'), ('ogrenci_isleri', 'Öğrenci İşleri Memuru'), ('diger', 'Diğer Personel')], default=['ogrenci'], max_length=100),
        ),
    ]
