# Generated by Django 5.0.14 on 2025-09-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duyurular', '0002_alter_duyuru_hedef_kitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duyuru',
            options={'ordering': ['olusturma_tarihi'], 'verbose_name': 'Duyuru', 'verbose_name_plural': 'Duyurular'},
        ),
    ]
