# Generated by Django 5.0.14 on 2025-07-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'SuperUser'), ('mudur', 'Müdür'), ('mudur_yardimcisi', 'Müdür Yardımcısı'), ('ogretmen', 'Öğretmen'), ('ogrenci', 'Öğrenci'), ('muhasebe', 'Muhasebe'), ('ogrenci_isleri', 'Öğrenci İşleri Memuru')], max_length=20),
        ),
    ]
