# Generated by Django 5.0.14 on 2025-09-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_brans_customuser_dogum_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sinif_seviye',
            field=models.CharField(blank=True, choices=[('anasinif', 'Ana Sınıfı'), ('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('5', '5. Sınıf'), ('6', '6. Sınıf'), ('7', '7. Sınıf'), ('8', '8. Sınıf')], max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sube',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='okul_no',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sicil_no',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
