# Generated by Django 5.0.14 on 2025-09-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_sinif_seviye_customuser_sube_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sicil_no',
        ),
        migrations.AddField(
            model_name='customuser',
            name='sigorta_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
