# Generated by Django 5.0.14 on 2025-09-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_sicil_no_customuser_sigorta_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='from_city',
            field=models.CharField(choices=[('Adana', 'Adana'), ('Adıyaman', 'Adıyaman'), ('Afyonkarahisar', 'Afyonkarahisar'), ('Ağrı', 'Ağrı'), ('Aksaray', 'Aksaray'), ('Amasya', 'Amasya'), ('Ankara', 'Ankara'), ('Antalya', 'Antalya'), ('Ardahan', 'Ardahan'), ('Van', 'Van'), ('Yalova', 'Yalova'), ('Yozgat', 'Yozgat'), ('Zonguldak', 'Zonguldak')], max_length=30),
        ),
    ]
