# Generated by Django 5.0.14 on 2025-09-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_from_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sinif',
        ),
    ]
