# Generated by Django 5.0.14 on 2025-09-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_sinif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='brans',
            field=models.CharField(blank=True, choices=[('okul_oncesi', 'Okul Öncesi Öğretmeni'), ('sinif_ogretmeni', 'Sınıf Öğretmeni'), ('matematik', 'Matematik'), ('turkce', 'Türkçe'), ('fen_bilimleri', 'Fen Bilimleri'), ('sosyal_bilgiler', 'Sosyal Bilgiler'), ('ingilizce', 'İngilizce'), ('din_kulturu', 'Din Kültürü ve Ahlak Bilgisi'), ('beden_egitimi', 'Beden Eğitimi'), ('muzik', 'Müzik'), ('gorsel_sanatlar', 'Görsel Sanatlar'), ('teknoloji_tasarim', 'Teknoloji ve Tasarım'), ('rehber_ogretmen', 'Rehber Öğretmen'), ('ozel_egitim', 'Özel Eğitim Öğretmeni'), ('diger', 'Diğer')], max_length=50),
        ),
    ]
