# Generated by Django 5.0.14 on 2025-09-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_brans'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gorev',
            field=models.CharField(blank=True, help_text='Diğer personel için görev tanımı', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'SuperUser'), ('mudur', 'Müdür'), ('mudur_yardimcisi', 'Müdür Yardımcısı'), ('ogretmen', 'Öğretmen'), ('ogrenci', 'Öğrenci'), ('muhasebe', 'Muhasebe'), ('ogrenci_isleri', 'Öğrenci İşleri Memuru'), ('diger', 'Diğer Personel')], max_length=20),
        ),
    ]
