# Generated by Django 5.0.14 on 2025-09-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_gorev_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_changed',
            field=models.BooleanField(default=False, verbose_name='Şifre değiştirildi mi?'),
        ),
    ]
