# Generated by Django 5.0.14 on 2025-09-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_password_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('erkek', 'Erkek'), ('kiz', 'Kız')], max_length=10, verbose_name='Cinsiyet'),
        ),
    ]
