# Generated by Django 5.0.14 on 2025-07-22 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dersler', '0001_initial'),
        ('ogrenciler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DersNotu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donem1_test', models.FloatField(blank=True, null=True)),
                ('donem1_yazili', models.FloatField(blank=True, null=True)),
                ('donem1_sozlu', models.FloatField(blank=True, null=True)),
                ('donem2_test', models.FloatField(blank=True, null=True)),
                ('donem2_yazili', models.FloatField(blank=True, null=True)),
                ('donem2_sozlu', models.FloatField(blank=True, null=True)),
                ('ortalama1', models.FloatField(blank=True, null=True)),
                ('ortalama2', models.FloatField(blank=True, null=True)),
                ('yil_sonu_ortalama', models.FloatField(blank=True, null=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dersler.ders')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogrenciler.ogrenci')),
            ],
            options={
                'unique_together': {('ogrenci', 'ders')},
            },
        ),
    ]
