# Generated by Django 5.0.14 on 2025-09-22 22:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0001_initial'),
        ('not_gir', '0001_initial'),
        ('ogrenciler', '0002_remove_ogrenci_ad_remove_ogrenci_adres_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dersnotu',
            options={'ordering': ['ogrenci__user__sinif_seviye', 'ogrenci__user__sube', 'ders__ad', 'ogrenci__user__last_name'], 'verbose_name': 'Ders Notu', 'verbose_name_plural': 'Ders Notları'},
        ),
        migrations.AddField(
            model_name='dersnotu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dersnotu',
            name='notlar',
            field=models.TextField(blank=True, null=True, verbose_name='Öğretmen Notları'),
        ),
        migrations.AddField(
            model_name='dersnotu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='dersnotu',
            name='ders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dersler.ders', verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='dersnotu',
            name='donem1_sozlu',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='1. Dönem Sözlü'),
        ),
        migrations.AlterField(
            model_name='dersnotu',
            name='donem1_test',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='1. Dönem Test'),
        ),
        migrations.AlterField(
            model_name='dersnotu',
            name='donem1_yazili',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='1. Dönem Yazılı'),
        ),
        migrations.AlterField(
            model_name='dersnotu',
            name='donem2_sozlu',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='2. Dönem Sözlü'),
        ),
        migrations.AlterField(
            model_name='dersnotu',
            name='donem2_test',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='2. Dönem Test'),
        ),
        migrations.AlterField(
            model_name='dersnotu',
            name='donem2_yazili',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='2. Dönem Yazılı'),
        ),
        migrations.AlterField(
            model_name='dersnotu',
            name='ogrenci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogrenciler.ogrenci', verbose_name='Öğrenci'),
        ),
        migrations.AlterField(
            model_name='dersnotu',
            name='ortalama1',
            field=models.FloatField(blank=True, null=True, verbose_name='1. Dönem Ortalaması'),
        ),
        migrations.AlterField(
            model_name='dersnotu',
            name='ortalama2',
            field=models.FloatField(blank=True, null=True, verbose_name='2. Dönem Ortalaması'),
        ),
        migrations.AlterField(
            model_name='dersnotu',
            name='yil_sonu_ortalama',
            field=models.FloatField(blank=True, null=True, verbose_name='Yıl Sonu Ortalaması'),
        ),
    ]
