# Generated by Django 5.0.14 on 2025-09-23 18:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ogrenciler', '0006_alter_ogretmensinifatama_atama_turu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devamsizlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='Devamsızlık Tarihi')),
                ('mazeret', models.CharField(choices=[('izinli', 'İzinli'), ('rapor', 'Sağlık Raporu'), ('olum_izni', 'Ölüm İzni'), ('aile_izni', 'Aile İzni'), ('mazeretsiz', 'Mazeretsiz')], default='mazeretsiz', max_length=20, verbose_name='Mazeret Türü')),
                ('ders_sayisi', models.PositiveIntegerField(default=1, verbose_name='Devamsız Olunan Ders Sayısı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kaydeden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden Kişi')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogrenciler.ogrenci', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Devamsızlık',
                'verbose_name_plural': 'Devamsızlıklar',
                'ordering': ['-tarih'],
                'unique_together': {('ogrenci', 'tarih')},
            },
        ),
    ]
