# Generated by Django 5.0.14 on 2025-07-22 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ogrenciler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devamsizlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donem', models.IntegerField(choices=[(1, '1. Dönem'), (2, '2. Dönem')], default=1)),
                ('mazeret', models.CharField(choices=[('rapor', 'Rapor'), ('turnuva', 'Turnuva'), ('olum_izni', 'Ölüm İzni'), ('hava_degisimi', 'Hava Değişimi'), ('mazeretsiz', 'Mazeretsiz')], default='rapor', max_length=30)),
                ('devamsizlik_tarihi', models.DateField()),
                ('gun_sayisi', models.IntegerField(blank=True, null=True)),
                ('donem1_devamsizlik', models.IntegerField(blank=True, null=True)),
                ('donem2_devamsizlik', models.IntegerField(blank=True, null=True)),
                ('yil_toplam_devamsizlik', models.IntegerField(blank=True, null=True)),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogrenciler.ogrenci')),
            ],
        ),
    ]
