# Generated by Django 5.0.14 on 2025-09-26 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonelIzin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izin_turu', models.CharField(choices=[('rapor', 'Rapor'), ('evlilik', 'Evlilik İzni'), ('refakat', 'Refakat İzni'), ('cenaze', 'Cenaze İzni'), ('mazeretsiz', 'Mazeretsiz'), ('yillik', 'Yıllık İzin')], max_length=20)),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Bitiş Tarihi')),
                ('aciklama', models.TextField(blank=True)),
                ('onaylandi', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personel', models.ForeignKey(limit_choices_to={'role__in': ['ogretmen', 'diger']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Personel İzin',
                'verbose_name_plural': 'Personel İzinler',
                'ordering': ['-baslangic_tarihi'],
            },
        ),
    ]
