# Generated by Django 5.0.14 on 2025-07-22 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dersler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20, unique=True)),
                ('dersler', models.ManyToManyField(blank=True, to='dersler.ders')),
            ],
        ),
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(blank=True, max_length=100, null=True)),
                ('soyad', models.CharField(blank=True, max_length=100, null=True)),
                ('dogum_tarihi', models.DateField()),
                ('adres', models.TextField()),
                ('memleket', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('kayit_tarihi', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sinif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ogrenciler.sinif')),
            ],
        ),
    ]
