# Generated by Django 5.0.14 on 2025-07-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenciler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrenci',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='ogrenci',
            name='adres',
        ),
        migrations.RemoveField(
            model_name='ogrenci',
            name='kayit_tarihi',
        ),
        migrations.RemoveField(
            model_name='ogrenci',
            name='memleket',
        ),
        migrations.RemoveField(
            model_name='ogrenci',
            name='soyad',
        ),
        migrations.RemoveField(
            model_name='ogrenci',
            name='telefon',
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
