# Generated by Django 5.0.14 on 2025-09-22 22:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0001_initial'),
        ('ogrenciler', '0002_remove_ogrenci_ad_remove_ogrenci_adres_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrenci',
            name='sinif',
        ),
        migrations.AlterModelOptions(
            name='ogrenci',
            options={'ordering': ['user__sinif_seviye', 'user__sube', 'user__last_name'], 'verbose_name': 'Öğrenci', 'verbose_name_plural': 'Öğrenciler'},
        ),
        migrations.RemoveField(
            model_name='ogrenci',
            name='dogum_tarihi',
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 22, 22, 37, 5, 597760, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='notlar',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='ozel_durum',
            field=models.TextField(blank=True, null=True, verbose_name='Özel Durum/Notlar'),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='veli_bilgileri',
            field=models.TextField(blank=True, null=True, verbose_name='Veli Bilgileri'),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'ogrenci'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SinifDersAtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinif_seviye', models.CharField(choices=[('9', '9. Sınıf'), ('10', '10. Sınıf'), ('11', '11. Sınıf'), ('12', '12. Sınıf')], max_length=2, unique=True, verbose_name='Sınıf Seviyesi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dersler', models.ManyToManyField(to='dersler.ders', verbose_name='Sınıf Dersleri')),
            ],
            options={
                'verbose_name': 'Sınıf Ders Ataması',
                'verbose_name_plural': 'Sınıf Ders Atamaları',
                'ordering': ['sinif_seviye'],
            },
        ),
        migrations.DeleteModel(
            name='Sinif',
        ),
    ]
