# Generated by Django 5.0.14 on 2025-09-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenciler', '0003_remove_ogrenci_sinif_alter_ogrenci_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinifdersatama',
            name='sinif_seviye',
            field=models.CharField(choices=[('anasinif', 'Ana Sınıfı'), ('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('5', '5. Sınıf'), ('6', '6. Sınıf'), ('7', '7. Sınıf'), ('8', '8. Sınıf')], max_length=10, unique=True, verbose_name='Sınıf Seviyesi'),
        ),
    ]
