# Generated by Django 5.0.14 on 2025-09-23 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0001_initial'),
        ('ogrenciler', '0004_alter_sinifdersatama_sinif_seviye'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OgretmenSinifAtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinif_seviye', models.CharField(choices=[('anasinif', 'Ana Sınıfı'), ('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('5', '5. Sınıf'), ('6', '6. Sınıf'), ('7', '7. Sınıf'), ('8', '8. Sınıf')], max_length=10, verbose_name='Sınıf Seviyesi')),
                ('sube', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True, verbose_name='Şube')),
                ('atama_turu', models.CharField(choices=[('sinif_ogretmeni', 'Sınıf Öğretmeni'), ('brans_ogretmeni', 'Branş Öğretmeni')], max_length=20, verbose_name='Atama Türü')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dersler', models.ManyToManyField(blank=True, to='dersler.ders', verbose_name='Sorumlu Olduğu Dersler')),
                ('ogretmen', models.ForeignKey(limit_choices_to={'role': 'ogretmen'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Öğretmen')),
            ],
            options={
                'verbose_name': 'Öğretmen Sınıf Ataması',
                'verbose_name_plural': 'Öğretmen Sınıf Atamaları',
                'unique_together': {('ogretmen', 'sinif_seviye', 'sube')},
            },
        ),
    ]
