# Generated by Django 5.0.14 on 2025-09-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenciler', '0005_ogretmensinifatama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogretmensinifatama',
            name='atama_turu',
            field=models.CharField(choices=[('okul_oncesi', 'Okul Öncesi Öğretmeni'), ('sinif_ogretmeni', 'Sınıf Öğretmeni'), ('brans_ogretmeni', 'Branş Öğretmeni')], max_length=20, verbose_name='Atama Türü'),
        ),
    ]
