# Generated by Django 5.0.14 on 2025-09-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenciler', '0006_alter_ogretmensinifatama_atama_turu'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ogretmensinifatama',
            unique_together=set(),
        ),
    ]
