# Generated by Django 5.0.14 on 2025-09-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ders',
            name='renk',
            field=models.CharField(choices=[('bg-danger', 'Kırmızı'), ('bg-primary', 'Mavi'), ('bg-success', 'Yeşil'), ('bg-warning', 'Sarı'), ('bg-info', 'Turkuaz'), ('bg-secondary', 'Gri'), ('bg-dark', 'Siyah')], default='bg-primary', max_length=20, verbose_name='Kart Rengi'),
        ),
    ]
