# Generated by Django 5.0.14 on 2025-09-26 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0002_ders_renk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DersProgrami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinif_seviye', models.CharField(max_length=10)),
                ('sube', models.CharField(max_length=1)),
                ('gun', models.CharField(choices=[('pazartesi', 'Pazartesi'), ('sali', 'Salı'), ('carsamba', 'Çarşamba'), ('persembe', 'Perşembe'), ('cuma', 'Cuma')], max_length=10)),
                ('saat', models.CharField(choices=[('1', '1. Ders (08:00-08:45)'), ('2', '2. Ders (09:00-09:45)'), ('3', '3. Ders (10:00-10:45)'), ('4', '4. Ders (11:00-11:45)'), ('5', '5. Ders (13:00-13:45)'), ('6', '6. Ders (14:00-14:45)')], max_length=1)),
                ('aktif', models.BooleanField(default=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dersler.ders')),
                ('ogretmen', models.ForeignKey(blank=True, limit_choices_to={'role': 'ogretmen'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sinif_seviye', 'sube', 'gun', 'saat'],
                'unique_together': {('sinif_seviye', 'sube', 'gun', 'saat')},
            },
        ),
    ]
