# Generated by Django 5.0.14 on 2025-09-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0003_dersprogrami'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dersprogrami',
            name='sinif_seviye',
            field=models.CharField(choices=[('anasinif', 'Ana Sınıfı'), ('1', '1. Sınıf'), ('2', '2. Sınıf'), ('3', '3. Sınıf'), ('4', '4. Sınıf'), ('5', '5. Sınıf'), ('6', '6. Sınıf'), ('7', '7. Sınıf'), ('8', '8. Sınıf')], max_length=10, verbose_name='Sınıf Seviyesi'),
        ),
        migrations.AlterField(
            model_name='dersprogrami',
            name='sube',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Şube'),
        ),
    ]
