# Generated by Django 5.0.14 on 2025-09-25 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dersler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Odev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinif_seviye', models.CharField(max_length=20, verbose_name='Sınıf')),
                ('sube', models.CharField(max_length=1, verbose_name='Şube')),
                ('baslik', models.CharField(max_length=200, verbose_name='Ödev Başlığı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('son_teslim_tarihi', models.DateField(verbose_name='Son Teslim Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dersler.ders', verbose_name='Ders')),
                ('ogretmen', models.ForeignKey(limit_choices_to={'role': 'ogretmen'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Öğretmen')),
            ],
            options={
                'verbose_name': 'Ödev',
                'verbose_name_plural': 'Ödevler',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
